// <copyright file="DecisionCore.cs" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

namespace OAPS.Mind;

using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using MUnique.OpenMU.AIPlayer;
using MUnique.OpenMU.AIPlayer.Decision;
using MUnique.OpenMU.AIPlayer.Scripting;

/// <summary>
/// 三轨决策核心 — OAPS Layer 5 心智引擎 (v4.0 Fugu)。
///
/// Track 1: RuleEngine — 规则驱动快速兜底 (<1ms)
/// Track 2: ScriptExecutor — 学习脚本执行 (~5ms)
/// Track 3: SoftRouter — 动态路由 (~10ms, Fugu)
///
/// 参考: OAPS-v4-Fugu-Fusion-Design.md §2.1
/// </summary>
public sealed class DecisionCore
{
    private readonly BehaviorInertiaEngine _inertia = new();
    private readonly ILogger _logger;

    public DecisionCore(ILogger? logger = null)
    {
        _logger = logger ?? NullLogger<DecisionCore>.Instance;
    }

    /// <summary>
    /// 三轨决策。T1→T2→T3 评估，学习规则优先。
    /// </summary>
    public async ValueTask<DecisionResult> DecideAsync(
        AiPlayer player,
        IGameAdapter adapter,
        RuleEngine ruleEngine,
        ScriptLibrary scriptLibrary,
        SoftRouter? softRouter = null)
    {
        // T1+T2: RuleEngine → ScriptLibrary 分发
        var ruleResult = ruleEngine.Evaluate(player, adapter);
        if (ruleResult is not null)
        {
            var rule = ruleResult.Rule;
            var module = scriptLibrary.Get(rule.ScriptId);

            if (module is not null && ruleResult.GeneratedMission is not null)
            {
                var stepResult = await module.ExecuteStepAsync(ruleResult.GeneratedMission).ConfigureAwait(false);
                _inertia.Record(rule.ScriptId, stepResult == StepResult.Completed);

                if (rule.AutoGenerated)
                {
                    _logger.LogInformation("[DCore] T1→T2 学习规则: {RuleId}→{ScriptId} result={Result}",
                        rule.RuleId, rule.ScriptId, stepResult);
                }

                return DecisionResult.RuleMatched(rule, stepResult);
            }

            // 规则匹配但无可用模块 → fallthrough to next track
        }

        // T3: SoftRouter 动态路由
        if (softRouter is not null)
        {
            // Approximate state from player context
            var pos = adapter.GetPlayerPosition();
            var hp = adapter.GetCurrentHp();
            var maxHp = adapter.GetMaxHp();
            var stateVector = new StateVector
            {
                HpPercent = maxHp > 0 ? (float)hp / maxHp : 0f,
                MpPercent = 1.0f,
                Level = player.Level,
                TargetCount = 0,
                IsAtSafeZone = false,
                InventorySlotsFree = 32,
            };

            var dist = softRouter.Evaluate(stateVector);
            if (dist.Logits.Length > 0)
            {
                var bestAction = softRouter.SelectBestAction(dist);
                var actionName = $"softrouter_action_{bestAction}";
                _logger.LogDebug("[DCore] T3: SoftRouter action={Action}", bestAction);
                return DecisionResult.SoftRouterAction(actionName, bestAction);
            }
        }

        return DecisionResult.NoAction();
    }

    /// <summary>三轨决策（向后兼容 — 被 CognitiveLoop 调用，当前未激活LLM推理）。</summary>
    public async ValueTask<DecisionResult> Decide(OAPS.World.WorldState state, PerceptContext? context = null, PersonalityEngine? personality = null)
    {
        // v4.0: 当前 Phase 未启用 LLM 推理，CognitiveLoop 返回 NoAction
        return DecisionResult.NoAction();
    }

    /// <summary>记录行为结果（向后兼容）。</summary>
    public void RecordActionResult(string actionName, bool success, OAPS.World.WorldState? state = null) => _inertia.Record(actionName, success);

    /// <summary>记录行为结果（惯性学习）。</summary>
    public void RecordActionResult(string actionName, bool success) => _inertia.Record(actionName, success);
}

/// <summary>决策结果。</summary>
public sealed record DecisionResult
{
    public string ActionName { get; init; } = "wait";
    public int Priority { get; init; } = 999;
    public string Reason { get; init; } = string.Empty;
    public bool IsLearnedRule { get; init; }
    public RuleDef? MatchedRule { get; init; }
    public StepResult ExecutionResult { get; init; }
    public object? Payload { get; init; }

    /// <summary>向后兼容：映射 ActionName 到 DecisionAction 枚举。</summary>
    public DecisionAction Action => ActionName switch
    {
        "combat" or "attack" => DecisionAction.Attack,
        "survival" or "patrol" => DecisionAction.Patrol,
        "inventory" or "pickup" => DecisionAction.Pickup,
        "quest" or "interact" => DecisionAction.Interact,
        "wait" => DecisionAction.Wait,
        _ => DecisionAction.Wait,
    };

    internal static DecisionResult RuleMatched(RuleDef rule, StepResult result) => new()
    {
        ActionName = rule.ScriptId,
        Priority = rule.Priority,
        Reason = $"{rule.RuleId} → {rule.ScriptId}",
        IsLearnedRule = rule.AutoGenerated,
        MatchedRule = rule,
        ExecutionResult = result,
    };

    internal static DecisionResult SoftRouterAction(string name, int actionIndex) => new()
    {
        ActionName = name,
        Priority = 10,
        Reason = $"SoftRouter choice index={actionIndex}",
    };

    internal static DecisionResult NoAction() => new()
    {
        ActionName = "wait",
        Priority = 999,
        Reason = "no matching rule or script",
    };
}

/// <summary>行为惯性引擎 — 重复成功固化为习惯。</summary>
public sealed class BehaviorInertiaEngine
{
    private readonly Dictionary<string, HabitRecord> _habits = new();

    public bool TryHabit(string actionName) =>
        _habits.TryGetValue(actionName, out var h) && h.Strength > 0.6f;

    public void Record(string actionName, bool success)
    {
        if (!_habits.TryGetValue(actionName, out var habit))
        {
            habit = new HabitRecord();
            _habits[actionName] = habit;
        }

        if (success) habit.SuccessCount++;
        else habit.SuccessCount = Math.Max(0, habit.SuccessCount - 1);

        habit.Strength = Math.Min(1.0f, habit.SuccessCount / 3f);
        habit.LastPerformed = DateTime.UtcNow;
    }
}

/// <summary>习惯记录。</summary>
public sealed class HabitRecord
{
    public int SuccessCount { get; set; }
    public float Strength { get; set; }
    public DateTime LastPerformed { get; set; } = DateTime.UtcNow;
}

/// <summary>决策动作枚举（向后兼容）。</summary>
public enum DecisionAction
{
    Wait, Attack, SkillAttack, Flee,
    UseHealthPotion, UseManaPotion, Pickup, Move, Interact, Patrol,
}
