// <copyright file="RuleEngine.cs" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

namespace MUnique.OpenMU.AIPlayer.Decision;

using System.IO;
using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.Extensions.Logging;
using MUnique.OpenMU.DataModel;
using MUnique.OpenMU.DataModel.Configuration.Items;
using MUnique.OpenMU.DataModel.Entities;
using MUnique.OpenMU.GameLogic;
using MUnique.OpenMU.GameLogic.Attributes;
using MUnique.OpenMU.GameLogic.Views;
using MUnique.OpenMU.Pathfinding;
using MUnique.OpenMU.AIPlayer.Knowledge;

/// <summary>
/// 规则引擎 — 条件评估 + 脚本选择 + MissionItem 生成。
/// 输入：角色状态。输出：符合条件且优先级最高的规则 → 生成 MissionItem → 由心跳服务调度执行。
/// </summary>
public sealed class RuleEngine
{
    private readonly ScriptLibrary _scriptLib;
    private readonly ILogger _logger;
    private readonly List<RuleDef> _rules;
    private readonly string _dataDir;

    /// <summary>
    /// Gets the read-only list of all registered rules.
    /// </summary>
    public IReadOnlyList<RuleDef> Rules => this._rules.AsReadOnly();

    /// <summary>
    /// Initializes a new instance of the <see cref="RuleEngine"/> class.
    /// 先尝试从 JSON 文件加载规则，失败时降级到内置默认规则。
    /// </summary>
    /// <param name="scriptLib">The script library to resolve script IDs.</param>
    /// <param name="logger">The logger.</param>
    public RuleEngine(ScriptLibrary scriptLib, ILogger logger)
    {
        this._scriptLib = scriptLib;
        this._logger = logger;
        this._rules = LoadDefaultRules();
        this._dataDir = AppContext.BaseDirectory;
        this.TryLoadFromAppDir();
    }

    /// <summary>
    /// 初始化规则引擎（无脚本库，仅用于接收学习规则）。
    /// 旁观者系统的共享规则引擎专用，不执行 Evaluate()。
    /// </summary>
    /// <param name="logger">The logger.</param>
    public RuleEngine(ILogger logger)
    {
        this._scriptLib = null!;
        this._logger = logger;
        this._rules = new List<RuleDef>();
        this._dataDir = AppContext.BaseDirectory;
    }

    /// <summary>
    /// 从 Decision/scripts-rules.json 加载规则，替换当前规则表。
    /// 供 RuleWatcherService 热重载调用。
    /// </summary>
    /// <param name="json">规则 JSON 字符串。</param>
    /// <returns>加载的规则数量。</returns>
    public int ReloadFromJson(string json)
    {
        var count = this.LoadFromJson(json);
        this._logger.LogInformation("[RuleEngine] 热重载 {Count} 条规则", count);
        return count;
    }

    /// <summary>
    /// 每次心跳调用：评估所有规则，返回匹配结果。
    /// 结果包含命中的规则定义和生成的 MissionItem（可为空）。
    /// </summary>
    /// <param name="player">The AI player to evaluate against.</param>
    /// <param name="adapter">The game adapter for state queries.</param>
    /// <returns>匹配结果，包含 RuleDef 和生成的 MissionItem；无匹配返回 null。</returns>
    /// <summary>
    /// 评估所有匹配的规则，返回规则集（用于构建当前任务阶段的脚本执行序列）。
    /// 实现"规则库→规则集→脚本序列"的决策流程。
    /// </summary>
    public List<RuleMatchResult> EvaluateAll(AiPlayer player, IGameAdapter adapter)
    {
        var results = new List<RuleMatchResult>();

        foreach (var rule in this._rules.OrderBy(r => r.Priority))
        {
            if (!MeetsLevel(player, rule)) continue;
            if (!MeetsClass(player, rule)) continue;
            if (!this.MeetsCondition(player, adapter, rule)) continue;

            var mission = this.GenerateMissionItem(rule);
            if (mission is not null)
            {
                results.Add(new RuleMatchResult(rule, mission));
            }
        }

        // 学习规则优先排序：AutoGenerated+Confidence>0.3 的规则排在前面
        results.Sort((a, b) =>
        {
            var aLearn = a.Rule.AutoGenerated && a.Rule.Confidence > 0.3f ? 0 : 1;
            var bLearn = b.Rule.AutoGenerated && b.Rule.Confidence > 0.3f ? 0 : 1;
            if (aLearn != bLearn) return aLearn.CompareTo(bLearn);
            return a.Rule.Priority.CompareTo(b.Rule.Priority);
        });

        return results;
    }

    /// <summary>向后兼容：返回最佳单条规则。</summary>
    public RuleMatchResult? Evaluate(AiPlayer player, IGameAdapter adapter)
    {
        var all = EvaluateAll(player, adapter);
        return all.FirstOrDefault();
    }

    /// <summary>
    /// 获取规则表的只读副本（用于调试/展示）。
    /// </summary>
    /// <returns>All registered rules.</returns>
    public IReadOnlyList<RuleDef> GetRules() => this._rules.AsReadOnly();

    /// <summary>
    /// 注入经验学习规则。自动标记为 AutoGenerated，优先级偏移 +1000 避免覆盖人工规则。
    /// </summary>
    /// <param name="learnedRules">要注入的学习规则列表。</param>
    public void AddLearnedRules(IEnumerable<RuleDef> learnedRules)
    {
        var count = 0;
        foreach (var rule in learnedRules)
        {
            // 自动生成的规则优先级偏移，避免覆盖人工配置的规则
            var adjusted = rule with
            {
                AutoGenerated = true,
                Priority = rule.Priority, // 保持原优先级，Evaluate 中学习规则优先匹配
            };
            this._rules.Add(adjusted);
            count++;
        }

        this._logger.LogInformation("[RuleEngine] 已注入 {Count} 条学习规则", count);
    }

    /// <summary>
    /// 注入单条已处理的规则（用于各 AI 角色从共享 RuleEngine 同步学习规则）。
    /// 不调整优先级偏移（调用者已处理）。
    /// </summary>
    public void AddSingleLearnedRule(RuleDef rule)
    {
        this._rules.Add(rule);
    }

    /// <summary>
    /// 从程序集目录的 Decision/scripts-rules.json 加载规则（开发/生产模式通用）。
    /// 失败时静默降级（保留内置规则）。
    /// </summary>
    public int TryLoadFromAppDir()
    {
        try
        {
            var filePath = Path.Combine(AppContext.BaseDirectory, "Decision", "scripts-rules.json");

            if (!File.Exists(filePath))
            {
                this._logger.LogDebug("[RuleEngine] 规则文件未找到 (Decision/scripts-rules.json)，使用内置规则");
                return 0;
            }

            var json = File.ReadAllText(filePath);
            var count = this.LoadFromJson(json);
            if (count > 0)
            {
                this._logger.LogInformation("[RuleEngine] 已从 {File} 加载 {Count} 条规则", filePath, count);
            }

            return count;
        }
        catch (Exception ex)
        {
            this._logger.LogWarning(ex, "[RuleEngine] JSON 规则文件加载失败，使用内置规则");
            return 0;
        }
    }

    /// <summary>
    /// 尝试加载经验系统生成的规则（rules_experience.json）。
    /// 追加到现有规则表，低置信度规则会被跳过。
    /// </summary>
    public void TryLoadExperienceRules()
    {
        try
        {
            var injector = new Experience.ExperienceRuleInjector(this._dataDir, this._logger);
            var expRules = injector.LoadExperienceRulesAsync().ConfigureAwait(false).GetAwaiter().GetResult();
            if (expRules.Count == 0) return;

            var added = 0;
            var skipped = 0;
            foreach (var rule in expRules)
            {
                // 自动生成的规则，置信度低于阈值时跳过
                if (rule.AutoGenerated && rule.Confidence < Experience.RuleCandidate.ConfidenceThreshold)
                {
                    skipped++;
                    continue;
                }

                // 去重：同ID的规则替换
                var idx = this._rules.FindIndex(r => r.RuleId == rule.RuleId);
                if (idx >= 0)
                {
                    this._rules[idx] = rule;
                }
                else
                {
                    this._rules.Add(rule);
                }

                added++;
            }

            if (added > 0)
            {
                this._logger.LogInformation("[RuleEngine] 已加载 {Added} 条经验规则 (跳过{Skips}条低置信度)", added, skipped);
            }
        }
        catch (Exception ex)
        {
            this._logger.LogDebug(ex, "[RuleEngine] 经验规则加载失败（首次使用无经验文件正常）");
        }
    }

    /// <summary>
    /// 从 JSON 字符串加载规则，替换当前规则表。
    /// </summary>
    /// <param name="json">JSON 格式的规则数组。</param>
    /// <returns>成功加载的规则数量。</returns>
    public int LoadFromJson(string json)
    {
        try
        {
            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true,
                ReadCommentHandling = JsonCommentHandling.Skip,
                AllowTrailingCommas = true,
            };

            // 支持两种格式：
            //   { "rules": [...] } — 文件格式
            //   [...] — 直接数组格式（兼容旧格式）
            List<RuleDefJson>? loaded;

            if (json.TrimStart().StartsWith("{", StringComparison.Ordinal))
            {
                // Wrap format: {"rules": [...]}
                var wrapper = JsonSerializer.Deserialize<RuleFileWrapper>(json, options);
                loaded = wrapper?.Rules;
            }
            else
            {
                // Array format: [...]
                loaded = JsonSerializer.Deserialize<List<RuleDefJson>>(json, options);
            }

            if (loaded is null || loaded.Count == 0)
            {
                this._logger.LogWarning("[RuleEngine] JSON 规则为空或格式无效，保留内置规则");
                return 0;
            }

            this._rules.Clear();
            foreach (var r in loaded)
            {
                this._rules.Add(r.ToRuleDef());
            }

            this._logger.LogInformation("[RuleEngine] 从 JSON 加载了 {Count} 条规则", this._rules.Count);
            return this._rules.Count;
        }
        catch (JsonException ex)
        {
            this._logger.LogError(ex, "[RuleEngine] JSON 规则解析失败，保留内置规则");
            return 0;
        }
    }

    /// <summary>
    /// 根据 RuleDef 生成对应的 MissionItem。
    /// Category 映射规则：survival/inventory/equip/skill/stat → MissionType.Survival;
    /// craft/quest → MissionType.Quest;
    /// 其他 → MissionType.Survival。
    /// </summary>
    /// <param name="rule">命中的规则定义。</param>
    /// <returns>生成的 MissionItem，可为 null（例如 survival 规则通常不需要生成独立任务）。</returns>
    public MissionItem? GenerateMissionItem(RuleDef rule)
    {
        var missionType = rule.Category.ToLowerInvariant() switch
        {
            "craft" or "quest" => MissionType.Quest,
            "learned" or "experience" => MissionType.Exploration, // 学习规则 → 探索任务
            _ => MissionType.Survival,
        };

        // Survival 类规则由心跳服务直接处理，不需要生成独立任务
        // 但 learned/experience 规则是旁观者学习的经验，必须生成Mission任务
        if (missionType == MissionType.Survival)
        {
            return null;
        }

        var mission = new MissionItem
        {
            Id = $"rule_{rule.RuleId}",
            Title = rule.Description,
            Priority = rule.Priority,
            Type = missionType,
            Module = rule.ScriptId,
            Status = MissionStatus.Pending,
        };

        // 复制 Parameters 到 MissionItem 的 Context
        if (rule.Parameters is { Count: > 0 })
        {
            foreach (var kvp in rule.Parameters)
            {
                mission.Context[kvp.Key] = kvp.Value;
            }
        }

        return mission;
    }

    /// <summary>
    /// 等级门控检查。
    /// </summary>
    private static bool MeetsLevel(AiPlayer player, RuleDef rule)
    {
        var level = player.Level;
        if (rule.MinLevel > 0 && level < rule.MinLevel)
        {
            return false;
        }

        if (rule.MaxLevel > 0 && level > rule.MaxLevel)
        {
            return false;
        }

        return true;
    }

    /// <summary>
    /// 职业门控检查。
    /// </summary>
    private static bool MeetsClass(AiPlayer player, RuleDef rule)
    {
        if (rule.RequiredClass is null)
        {
            return true;
        }

        var charClass = player.SelectedCharacter?.CharacterClass?.Name.ValueInNeutralLanguage;
        if (charClass is null)
        {
            return false;
        }

        return charClass.Contains(rule.RequiredClass, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// 条件表达式评估 — 将字符串条件映射到具体检查逻辑。
    /// </summary>
    private bool MeetsCondition(AiPlayer player, IGameAdapter adapter, RuleDef rule)
    {
        var inventory = player.Inventory;
        if (inventory is null)
        {
            return false;
        }

        return rule.Condition switch
        {
            "always" => true,
            "hp_low" => MeetsHpLow(adapter),
            "free_slots_lt_4" => CheckFreeSlots(inventory),
            "has_better_equip" => HasBetterEquip(inventory, player),
            "has_learnable_skill" => HasLearnableSkill(inventory) && inventory.FreeSlots.Count() >= 1,
            "has_stat_points" => HasStatPoints(player),
            "can_craft_wing2" => CanCraftWing2(inventory),
            "can_craft_wing3" => CanCraftWing3(inventory),
            "can_craft_ticket" => CanCraftTicket(inventory),
            "can_craft_chaos_weapon" => CanCraftChaosWeapon(inventory),
            "can_craft_equip_upgrade" => CanCraftEquipUpgrade(inventory),
            "inventory_full" => inventory.FreeSlots.Count() < 2,
            "level_ge" => player.Level >= GetIntParam(rule, "level"),
            "level_lt" => player.Level < GetIntParam(rule, "level"),
            "has_item_group" => HasItemInGroup(inventory, GetIntParam(rule, "group")),
            "has_active_quest" => adapter.GetActiveQuests().Count > 0,
            // P2 新增条件类型
            "map_in" => adapter.GetCurrentMap()?.MapId == GetIntParam(rule, "mapNumber"),
            "gold_lt" => player.Money < GetIntParam(rule, "amount"),
            "has_item_by_name" => HasItemByName(inventory, GetStringParam(rule, "itemName")),
            "level_range" => player.Level >= GetIntParam(rule, "min") && player.Level <= GetIntParam(rule, "max"),
            // Learned rule conditions: "on_map_N" → check if AI is on map N
            _ when rule.Condition.StartsWith("on_map_") =>
                int.TryParse(rule.Condition["on_map_".Length..], out var mapNum)
                && adapter.GetCurrentMap()?.Definition.Number == mapNum,
            _ => false,
        };
    }

    /// <summary>
    /// 检查 HP 是否低于阈值（60%）并记录调试日志。
    /// </summary>
    private bool MeetsHpLow(IGameAdapter adapter)
    {
        var hp = adapter.GetCurrentHp();
        var maxHp = adapter.GetMaxHp();
        var ratio = maxHp > 0 ? (float)hp / maxHp : 0;
        this._logger.LogDebug("[RuleEngine] hp_low check: HP={Hp}/{MaxHp} ratio={Ratio:F3} threshold=0.6", hp, maxHp, ratio);
        return maxHp > 0 && ratio < 0.6f;
    }

    /// <summary>
    /// 检查背包空格数并记录日志（用于调试 auto_equip 被哪个条件拦截）。
    /// </summary>
    private static bool CheckFreeSlots(IInventoryStorage inventory)
    {
        return inventory.FreeSlots.Count() < 4;
    }

    /// <summary>
    /// 获取规则参数中的整数值。
    /// </summary>
    private static int GetIntParam(RuleDef rule, string key, int defaultValue = 0)
    {
        if (rule.Parameters is not null && rule.Parameters.TryGetValue(key, out var valueStr) &&
            int.TryParse(valueStr, out var value))
        {
            return value;
        }

        return defaultValue;
    }

    /// <summary>
    /// 获取规则参数中的字符串值。
    /// </summary>
    private static string? GetStringParam(RuleDef rule, string key)
    {
        if (rule.Parameters is not null && rule.Parameters.TryGetValue(key, out var value))
        {
            return value;
        }

        return null;
    }

    /// <summary>
    /// 检查背包中是否有匹配名称的物品。
    /// </summary>
    private static bool HasItemByName(IInventoryStorage inventory, string? itemName)
    {
        if (string.IsNullOrEmpty(itemName)) return false;
        return inventory.Items.Any(i =>
            i.Definition?.Name is not null &&
            i.Definition.Name.ToString()?.Contains(itemName, StringComparison.OrdinalIgnoreCase) == true);
    }

    /// <summary>
    /// 检查背包中是否有指定 Group 的物品。
    /// </summary>
    private static bool HasItemInGroup(IInventoryStorage inventory, int group)
    {
        return inventory.Items.Any(i => i.Definition?.Group == group);
    }

    /// <summary>
    /// 检查是否背包中有比身上同部位评分更高的装备。
    /// 如果目标装备位为空位，直接返回 true（可穿）。
    /// </summary>
    private bool HasBetterEquip(IInventoryStorage inventory, AiPlayer player)
    {
        var bagItems = 0;
        foreach (var item in inventory.Items)
        {
            if (item.Definition is null)
            {
                continue;
            }

            // Skip already equipped items
            if (item.ItemSlot <= InventoryConstants.LastEquippableItemSlotIndex)
            {
                continue;
            }

            bagItems++;
            var def = item.Definition;

            this._logger.LogTrace("[HasBetterEquip] bagItem slot={Slot}, group={Group}, number={Number}, name={Name}",
                item.ItemSlot, def.Group, def.Number, def.Name);

            if (def.ItemSlot is null)
            {
                continue;
            }

            // 确定这个物品属于哪个装备位
            var targetSlot = def.ItemSlot.ItemSlots?.FirstOrDefault(s => s <= InventoryConstants.LastEquippableItemSlotIndex);
            if (targetSlot is null)
            {
                this._logger.LogTrace("[HasBetterEquip] slot={Slot} ({Name}): targetSlot is null (equip slot mapping)", item.ItemSlot, def.Name);
                continue;
            }

            // 找身上这个部位已装备的物品
            // 先过滤装备格(0-11)中的物品，再找目标槽位
            var equippedItems = inventory.Items.Where(i => i.ItemSlot <= InventoryConstants.LastEquippableItemSlotIndex).ToList();
            var currentEquipped = equippedItems.FirstOrDefault(i => i.ItemSlot == targetSlot.Value);
            if (currentEquipped is null)
            {
                this._logger.LogDebug("[HasBetterEquip] slot={Slot} ({Name}) → empty equip slot, WOULD EQUIP",
                    item.ItemSlot, def.Name);
                return true; // 空位，直接可穿
            }

            // 对比评分
            var dir = player.BuildDirection;
            var newScore = ScoreEquipQuality(item, dir);
            var oldScore = ScoreEquipQuality(currentEquipped, dir);
            this._logger.LogTrace("[HasBetterEquip] slot={Slot} ({Name}) score={NewScore} vs equipped({EquipName}) score={OldScore}",
                item.ItemSlot, def.Name, newScore, currentEquipped.Definition?.Name ?? "?", oldScore);
            if (newScore > oldScore)
            {
                this._logger.LogDebug("[HasBetterEquip] slot={Slot} ({Name}) score={New} > equipped({EquipName}) score={Old}, WOULD EQUIP",
                    item.ItemSlot, def.Name, newScore, currentEquipped.Definition?.Name ?? "?", oldScore);
                return true;
            }
        }

        this._logger.LogDebug("[HasBetterEquip] no better equip found, bagItems={BagItems}", bagItems);
        return false;
    }

    /// <summary>
    /// 评分装备品质，用于对比两件装备好坏。
    /// 复用 EquipmentCompareService.ScoreEquipQuality 相同逻辑（含基础属性评分）。
    /// </summary>
    private static float ScoreEquipQuality(Item item)
    {
        return EquipmentCompareService.ScoreEquipQuality(item);
    }

    /// <summary>
    /// 带 BuildDirection 的评分 — 根据 build 方向调整攻击/防御权重。
    /// </summary>
    private static float ScoreEquipQuality(Item item, Knowledge.BuildDirection? direction)
    {
        return EquipmentCompareService.ScoreEquipQuality(item, direction);
    }

    /// <summary>
    /// 检查是否有可学习的技能书（Group=15）。
    /// </summary>
    private static bool HasLearnableSkill(IInventoryStorage inventory)
    {
        var itemDef = inventory.Items.FirstOrDefault(i => i.Definition?.Group == 15);
        return itemDef is not null;
    }

    /// <summary>
    /// 检查是否有未分配的属性点。
    /// </summary>
    private static bool HasStatPoints(AiPlayer player)
    {
        // Simple heuristic: level 1 base = 25 total, +5 per level
        return player.Level > 1;
    }

    /// <summary>
    /// 有翅膀2级合成材料。
    /// </summary>
    private static bool CanCraftWing2(IInventoryStorage inventory)
    {
        return HasItemName(inventory, "洛克之羽") && HasItemName(inventory, "混沌");
    }

    /// <summary>
    /// 有翅膀3级合成材料。
    /// </summary>
    private static bool CanCraftWing3(IInventoryStorage inventory)
    {
        return HasItemName(inventory, "神鹰羽毛") &&
               HasItemName(inventory, "神鹰火种") &&
               HasItemName(inventory, "混沌");
    }

    /// <summary>
    /// 有门票合成材料。
    /// </summary>
    private static bool CanCraftTicket(IInventoryStorage inventory)
    {
        return HasItemName(inventory, "恶魔广场通行证");
    }

    /// <summary>
    /// 有混沌武器合成材料。
    /// </summary>
    private static bool CanCraftChaosWeapon(IInventoryStorage inventory)
    {
        return HasItemName(inventory, "混沌") &&
               inventory.Items.Any(i => i.Definition?.Group is >= 0 and <= 6);
    }

    /// <summary>
    /// 有装备强化材料。
    /// </summary>
    private static bool CanCraftEquipUpgrade(IInventoryStorage inventory)
    {
        return inventory.Items.Any(i => i.Definition?.Group == 14 && (i.Definition?.Number is 13 or 14 or 31));
    }

    /// <summary>
    /// Helper: 检查背包中是否有匹配名称的物品（通过 ValueInNeutralLanguage）。
    /// </summary>
    private static bool HasItemName(IInventoryStorage inventory, string name)
    {
        return inventory.Items.Any(i =>
            !string.IsNullOrEmpty(i.Definition?.Name.ValueInNeutralLanguage) &&
            i.Definition.Name.ValueInNeutralLanguage == name);
    }

    /// <summary>
    /// 加载默认规则表 — 内置规则（JSON 加载失败时的 fallback）。
    /// </summary>
    private static List<RuleDef> LoadDefaultRules() => new()
    {
        // ===== 生存（最高优先级）=====
        new("survival_hp", 1, "survival", "hp_low", "survival", 0, 0, null, null, "血量低→喝红"),

        // ===== 背包空间（必须足够）=====
        new("inventory_cleanup", 10, "inventory", "free_slots_lt_4", "survival", 0, 0, null, null, "空格<4→回城清理"),

        // ===== 装备（自动成长）=====
        new("auto_equip", 20, "equip", "has_better_equip", "equip_compare", 0, 0, null, null, "背包有更好装备→换上"),

        // ===== 技能（自动成长）=====
        new("learn_skill", 25, "skill", "has_learnable_skill", "skill_learn", 0, 0, null, null, "有技能书→学习"),

        // ===== 合成（按材料）=====
        new("craft_wing2", 40, "craft", "can_craft_wing2", "crafting_executor", 80, 0, null, "洛克之羽+混沌", "有2级翅膀材料→合成"),
        new("craft_wing3", 40, "craft", "can_craft_wing3", "crafting_executor", 130, 0, null, "神鹰羽毛+神鹰火种+混沌", "有3级翅膀材料→合成"),

        // ===== 任务（按状态）=====
        new("quest_auto", 60, "quest", "has_active_quest", "quest_executor", 0, 0, null, null, "有活跃任务→优先执行"),

        // ===== 兜底（最低优先级）=====
        new("survival_farm", 90, "survival", "always", "survival", 0, 0, null, null, "无事可做→生存刷怪"),
    };
}

/// <summary>
/// JSON 文件包装器（支持 {"rules": [...]} 格式）。
/// </summary>
internal class RuleFileWrapper
{
    [JsonPropertyName("rules")]
    public List<RuleDefJson> Rules { get; set; } = new();
}

/// <summary>
/// JSON 规则定义的数据传输对象。
/// 与 <see cref="RuleDef"/> 一一对应，支持从 JSON 反序列化。
/// </summary>
internal class RuleDefJson
{
    /// <summary>规则唯一标识。</summary>
    [JsonPropertyName("ruleId")]
    public string RuleId { get; set; } = string.Empty;

    /// <summary>优先级 — 越小越优先。</summary>
    [JsonPropertyName("priority")]
    public int Priority { get; set; }

    /// <summary>规则分类。</summary>
    [JsonPropertyName("category")]
    public string Category { get; set; } = string.Empty;

    /// <summary>条件表达式。</summary>
    [JsonPropertyName("condition")]
    public string Condition { get; set; } = string.Empty;

    /// <summary>条件满足时要调用的脚本 ID。</summary>
    [JsonPropertyName("scriptId")]
    public string ScriptId { get; set; } = string.Empty;

    /// <summary>最低触发等级。</summary>
    [JsonPropertyName("minLevel")]
    public int MinLevel { get; set; }

    /// <summary>最高触发等级。</summary>
    [JsonPropertyName("maxLevel")]
    public int MaxLevel { get; set; }

    /// <summary>限制职业。</summary>
    [JsonPropertyName("requiredClass")]
    public string? RequiredClass { get; set; }

    /// <summary>需要什么物品。</summary>
    [JsonPropertyName("itemRequired")]
    public string? ItemRequired { get; set; }

    /// <summary>规则说明。</summary>
    [JsonPropertyName("description")]
    public string Description { get; set; } = string.Empty;

    /// <summary>传给脚本的参数键值对。</summary>
    [JsonPropertyName("parameters")]
    public Dictionary<string, string>? Parameters { get; set; }

    /// <summary>是否由经验系统自动生成。</summary>
    [JsonPropertyName("autoGenerated")]
    public bool AutoGenerated { get; set; }

    /// <summary>置信度 0~1。自动生成的规则低于阈值时不生效。</summary>
    [JsonPropertyName("confidence")]
    public float Confidence { get; set; } = 1.0f;

    /// <summary>
    /// 转换为 RuleDef 记录。
    /// </summary>
    public RuleDef ToRuleDef() => new(
        this.RuleId,
        this.Priority,
        this.Category,
        this.Condition,
        this.ScriptId,
        this.MinLevel,
        this.MaxLevel,
        this.RequiredClass,
        this.ItemRequired,
        this.Description,
        this.Parameters,
        this.AutoGenerated,
        this.Confidence);
}
