// <copyright file="RuleDef.cs" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

namespace MUnique.OpenMU.AIPlayer.Decision;

/// <summary>
/// 单条规则 — 条件→脚本映射。
/// 规则表是配置驱动的（可存在 DB 或 JSON），定义"什么条件下执行什么脚本"。
///
/// 经验也是规则，只是置信度不同：
///   置信度 ≥ 0.6 → 写入 rules_experience.json，规则引擎可用
///   置信度 ≥ 0.9 → 可提升到 rules_default.json，变成系统级规则
///   置信度 &lt; 0.6 → 暂不启用（等更多样本）
/// </summary>
/// <param name="RuleId">规则唯一标识，如 "auto_equip_better", "learn_skill_from_inv"。</param>
/// <param name="Priority">优先级 — 越小越优先。</param>
/// <param name="Category">规则分类 — "equip" / "skill" / "craft" / "stat" / "event" / "inventory" / "survival"。</param>
/// <param name="Condition">条件表达式 — 由 RuleEngine 的条件评估器解析。</param>
/// <param name="ScriptId">条件满足时要调用的脚本 ID。</param>
/// <param name="MinLevel">最低触发等级（0=不限制）。</param>
/// <param name="MaxLevel">最高触发等级（0=不限制）。</param>
/// <param name="RequiredClass">限制职业（null=不限）。</param>
/// <param name="ItemRequired">需要什么物品（null=不限）。</param>
/// <param name="Description">规则说明。</param>
/// <param name="Parameters">传给脚本的参数键值对。例如 {"targetGroup": "15"} 表示技能书组。</param>
/// <param name="AutoGenerated">是否由经验系统自动生成。false=人工/系统内置。</param>
/// <param name="Confidence">置信度 0~1。自动生成的规则低于阈值时不生效。</param>
public record RuleDef(
    string RuleId,
    int Priority,
    string Category,
    string Condition,
    string ScriptId,
    int MinLevel,
    int MaxLevel,
    string? RequiredClass,
    string? ItemRequired,
    string Description,
    Dictionary<string, string>? Parameters = null,
    bool AutoGenerated = false,
    float Confidence = 1.0f);
