[Server]
; 客户端连接 GameServer 的端口和 IP
ClientPort=55901
ClientIP=127.0.0.1

[ConnectServer]
; ConnectServer 监听起始端口
StartPort=44406

[GameServer]
; GameServer 监听起始端口，以及默认启动数量
StartPort=55901
Count=3

[ChatServer]
; ChatServer 监听端口
Port=55980
