// <copyright file="SpecVerificationTests.cs" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

namespace MUnique.OpenMU.AIPlayer.Tests;

using System.Diagnostics;
using System.IO;
using System.Reflection;
using System.Xml.Linq;
using MUnique.OpenMU.Pathfinding;

/// <summary>
/// WIKI 可执行化测试 — 将 WIKI 规范层（Spec）转为 CI/CD 自动门禁。
///
/// 覆盖的规范条目：
///   1. XML 文档注释完整性 — 所有 public 类型和方法必须有 XML doc 注释
///   2. Async 命名规范 — 所有返回 Task/ValueTask 的 public 方法名必须以 Async 结尾
///   3. 危险区未修改 — Network/, Packet/, Memory/ 目录未被修改
///   4. 路径验证规则 — walkability、adjacency、bounds、end-at-target、MaxPathLength ≤ 128
/// </summary>
[TestFixture]
public class SpecVerificationTests
{
    private static Assembly AIPlayerAssembly => typeof(AiPlayer).Assembly;

    private static readonly string[] DangerousNamespaces =
    {
        "MUnique.OpenMU.Network",
        "MUnique.OpenMU.Packet",
        "MUnique.OpenMU.Memory",
    };

    #region Test 1: XML Documentation Completeness

    /// <summary>
    /// Verifies that all public types in the AIPlayer assembly have XML documentation comments.
    /// Loads the XML doc file generated by the build and checks each exported type for a matching member entry.
    /// </summary>
    [Test]
    public void AllPublicTypesAndMethodsHaveXmlDocs()
    {
        var assembly = AIPlayerAssembly;
        var xmlPath = Path.ChangeExtension(assembly.Location, ".xml");

        if (!File.Exists(xmlPath))
        {
            Assert.Inconclusive(
                $"XML documentation file not found at: {xmlPath}. " +
                "Build with <DocumentationFile> or <GenerateDocumentationFile> enabled in the AIPlayer project.");
            return;
        }

        var doc = XDocument.Load(xmlPath);
        var documentedMembers = doc.Root?
            .Element("members")?
            .Elements("member")
            .Select(m => m.Attribute("name")?.Value)
            .Where(v => v is not null)
            .ToHashSet()! ?? new HashSet<string?>();

        var violations = new List<string>();

        foreach (var type in assembly.GetExportedTypes().OrderBy(t => t.FullName))
        {
            var typeDocKey = $"T:{type.FullName}";
            if (!documentedMembers.Contains(typeDocKey))
            {
                violations.Add($"Type '{type.FullName}' is missing XML documentation.");
            }

            // Check constructors
            foreach (var ctor in type.GetConstructors(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static))
            {
                var ctorDocKey = GetMethodDocKey(ctor);
                if (!documentedMembers.Contains(ctorDocKey))
                {
                    violations.Add($"  Constructor '{type.FullName}(...)' is missing XML documentation.");
                }
            }

            // Check methods (skip property get/set accessors and compiler-generated methods)
            foreach (var method in type.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly))
            {
                if (method.IsSpecialName)
                {
                    continue;
                }

                if (method.DeclaringType == typeof(object))
                {
                    continue;
                }

                var methodDocKey = GetMethodDocKey(method);
                if (!documentedMembers.Contains(methodDocKey))
                {
                    violations.Add($"  Method '{type.FullName}.{method.Name}' is missing XML documentation.");
                }
            }

            // Check properties
            foreach (var prop in type.GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly))
            {
                var propDocKey = $"P:{prop.DeclaringType?.FullName}.{prop.Name}";
                if (!documentedMembers.Contains(propDocKey))
                {
                    violations.Add($"  Property '{type.FullName}.{prop.Name}' is missing XML documentation.");
                }
            }

            // Check events
            foreach (var evt in type.GetEvents(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly))
            {
                var evtDocKey = $"E:{evt.DeclaringType?.FullName}.{evt.Name}";
                if (!documentedMembers.Contains(evtDocKey))
                {
                    violations.Add($"  Event '{type.FullName}.{evt.Name}' is missing XML documentation.");
                }
            }
        }

        Assert.That(
            violations,
            Is.Empty,
            $"Found {violations.Count} undocumented public API member(s):\n{string.Join("\n", violations.Take(100))}");
    }

    #endregion

    #region Test 2: Async Naming Convention

    /// <summary>
    /// Verifies that all public methods returning <see cref="Task"/>, <see cref="Task{T}"/>,
    /// <see cref="ValueTask"/>, or <see cref="ValueTask{T}"/> have names ending with "Async".
    /// This follows the standard .NET async naming convention (VSTHRD100 / AsyncNaming).
    /// </summary>
    [Test]
    public void AllAsyncMethodsEndWithAsyncSuffix()
    {
        var assembly = AIPlayerAssembly;
        var violations = new List<string>();

        foreach (var type in assembly.GetExportedTypes())
        {
            foreach (var method in type.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly))
            {
                if (method.IsSpecialName)
                {
                    continue;
                }

                if (method.DeclaringType == typeof(object))
                {
                    continue;
                }

                var returnType = method.ReturnType;
                bool isAsync = returnType == typeof(Task)
                    || returnType == typeof(ValueTask)
                    || (returnType.IsGenericType && (
                        returnType.GetGenericTypeDefinition() == typeof(Task<>)
                        || returnType.GetGenericTypeDefinition() == typeof(ValueTask<>)));

                if (isAsync && !method.Name.EndsWith("Async", StringComparison.Ordinal))
                {
                    violations.Add($"{type.FullName}.{method.Name}");
                }
            }
        }

        Assert.That(
            violations,
            Is.Empty,
            $"Methods returning Task/ValueTask without 'Async' suffix ({violations.Count}):\n{string.Join("\n", violations)}");
    }

    #endregion

    #region Test 3: Dangerous Zones Not Modified

    /// <summary>
    /// Verifies that the AIPlayer assembly does not depend on or contain types
    /// from dangerous zone namespaces: Network/, Packet/, Memory/.
    /// These are protocol-layer concerns that must not be modified by AI logic.
    /// </summary>
    [Test]
    public void DangerousZonesNotModified()
    {
        var assembly = AIPlayerAssembly;
        var violations = new List<string>();

        // 1. Check referenced assemblies for dangerous namespaces
        foreach (var refAssembly in assembly.GetReferencedAssemblies())
        {
            foreach (var dangerousNs in DangerousNamespaces)
            {
                if (refAssembly.Name is not null
                    && refAssembly.Name.StartsWith(dangerousNs, StringComparison.OrdinalIgnoreCase))
                {
                    violations.Add($"Assembly references dangerous zone: {refAssembly.Name}");
                }
            }
        }

        // 2. Check all types in the assembly for dangerous namespace usage
        foreach (var type in assembly.GetTypes())
        {
            foreach (var dangerousNs in DangerousNamespaces)
            {
                if (type.FullName is not null
                    && type.FullName.StartsWith(dangerousNs, StringComparison.OrdinalIgnoreCase))
                {
                    violations.Add($"Type '{type.FullName}' is in a dangerous zone namespace.");
                }
            }
        }

        // 3. Try git log for the dangerous directories (if git is available)
        try
        {
            var process = new Process
            {
                StartInfo = new ProcessStartInfo
                {
                    FileName = "git",
                    Arguments = "log --oneline --all -- 'Network/' 'Packet/' 'Memory/'",
                    WorkingDirectory = Path.Combine(
                        AppContext.BaseDirectory, "..", "..", "..", "..", "..", "..", ".."),
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    UseShellExecute = false,
                    CreateNoWindow = true,
                },
            };

            process.Start();
            var output = process.StandardOutput.ReadToEnd();
            process.WaitForExit(5000);

            if (process.ExitCode == 0 && !string.IsNullOrWhiteSpace(output))
            {
                var commits = output.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries);
                violations.AddRange(
                    commits.Select(c => $"Git detects dangerous zone change: {c}"));
            }
        }
        catch
        {
            // git not available — fall back to reflection checks above
        }

        Assert.That(
            violations,
            Is.Empty,
            $"Dangerous zone violations ({violations.Count}):\n{string.Join("\n", violations)}");
    }

    #endregion

    #region Test 4: Pathfinding Validation Rules

    /// <summary>
    /// Verifies that pathfinding never includes unwalkable (blocked) tiles.
    /// A tile is unwalkable when its terrain grid value is 0.
    /// </summary>
    [Test]
    public void PathValidation_Walkability()
    {
        var (path, grid) = RunBasicPathfindingTest();

        foreach (var node in path)
        {
            byte cellValue = grid[node.X, node.Y];

            // Highest bit is safezone flag; lower 7 bits is cost. Zero cost = blocked.
            const byte costBitMask = 0b0111_1111;
            Assert.That(
                (cellValue & costBitMask),
                Is.GreaterThan(0),
                $"Path includes unwalkable tile at ({node.X}, {node.Y}): grid value = {cellValue}");
        }
    }

    /// <summary>
    /// Verifies that consecutive nodes in the path are adjacent
    /// (Chebyshev distance = 1, supporting both cardinal and diagonal moves).
    /// </summary>
    [Test]
    public void PathValidation_Adjacency()
    {
        var (path, _) = RunBasicPathfindingTest();
        Assert.That(path, Has.Count.GreaterThanOrEqualTo(2), "Path should have at least 2 nodes for adjacency test.");

        for (int i = 1; i < path.Count; i++)
        {
            var prev = path[i - 1];
            var curr = path[i];
            int dx = Math.Abs(curr.X - prev.X);
            int dy = Math.Abs(curr.Y - prev.Y);
            int chebyshev = Math.Max(dx, dy);

            Assert.That(
                chebyshev,
                Is.EqualTo(1),
                $"Non-adjacent path steps at index {i}: ({prev.X},{prev.Y}) -> ({curr.X},{curr.Y}), Chebyshev distance = {chebyshev}");
        }
    }

    /// <summary>
    /// Verifies that all path nodes fall within the terrain grid bounds.
    /// </summary>
    [Test]
    public void PathValidation_Bounds()
    {
        var (path, grid) = RunBasicPathfindingTest();
        int width = grid.GetLength(0);
        int height = grid.GetLength(1);

        foreach (var node in path)
        {
            Assert.That(node.X, Is.LessThan(width), $"Path node X={node.X} exceeds grid width={width}");
            Assert.That(node.Y, Is.LessThan(height), $"Path node Y={node.Y} exceeds grid height={height}");
        }
    }

    /// <summary>
    /// Verifies that the path ends at the specified target position.
    /// </summary>
    [Test]
    public void PathValidation_EndAtTarget()
    {
        Point start = new(5, 5);
        Point target = new(15, 15);
        var (path, _) = RunBasicPathfindingTest(start, target);

        var lastNode = path[^1];
        Assert.That(
            lastNode.Point,
            Is.EqualTo(target),
            $"Path end ({lastNode.X},{lastNode.Y}) does not match target ({target.X},{target.Y})");
    }

    /// <summary>
    /// Verifies that the path length does not exceed the maximum of 128 nodes.
    /// </summary>
    [Test]
    public void PathValidation_MaxPathLength()
    {
        var (path, _) = RunBasicPathfindingTest();
        Assert.That(
            path.Count,
            Is.LessThanOrEqualTo(128),
            $"Path length ({path.Count}) exceeds maximum allowed (128)");
    }

    /// <summary>
    /// Combined pathfinding validation test that verifies all five rules simultaneously.
    /// This is the main entry point for CI validation of the pathfinding specification.
    /// </summary>
    [Test]
    public void PathValidation_AllRules()
    {
        // Test multiple start/target configurations
        var testCases = new[]
        {
            new { Start = new Point(5, 5), Target = new Point(15, 15) },
            new { Start = new Point(1, 1), Target = new Point(30, 20) },
            new { Start = new Point(0, 0), Target = new Point(40, 30) },
        };

        foreach (var testCase in testCases)
        {
            var (path, grid) = RunBasicPathfindingTest(testCase.Start, testCase.Target);
            ValidatePath(path, grid, testCase.Start, testCase.Target);
        }
    }

    /// <summary>
    /// Tests pathfinding with blocked start position — the start node itself is
    /// on an unwalkable tile, but the pathfinder should still be able to leave it
    /// because it only checks walkability of neighbor tiles during expansion.
    /// The returned path's first node may be the blocked start; we verify all
    /// subsequent nodes are walkable.
    /// </summary>
    [Test]
    public void PathValidation_BlockedStart_SubsequentNodesAreWalkable()
    {
        var grid = CreateDefaultGrid();
        var start = new Point(0, 0);
        var target = new Point(15, 15);

        // Block the start position only
        grid[start.X, start.Y] = 0;

        var network = new TestGridNetwork();
        var pathFinder = new PathFinder(network);
        var result = pathFinder.FindPath(start, target, grid, false);

        Assert.That(result, Is.Not.Null, "PathFinder should handle blocked start (returns a path).");

        const byte costBitMask = 0b0111_1111;
        for (int i = 1; i < result!.Count; i++)
        {
            Assert.That(
                (grid[result[i].X, result[i].Y] & costBitMask),
                Is.GreaterThan(0),
                $"Subsequent path node at index {i} ({result[i].X},{result[i].Y}) is unwalkable.");
        }
    }

    /// <summary>
    /// Tests pathfinding with blocked target position — the pathfinder checks
    /// node position equality (not walkability) to determine arrival, so a path
    /// may end at a blocked target. We verify that all tiles except the final
    /// target tile are walkable.
    /// </summary>
    [Test]
    public void PathValidation_BlockedEnd_PenultimateNodesAreWalkable()
    {
        var grid = CreateDefaultGrid();
        var start = new Point(5, 5);
        var target = new Point(0, 0);

        // Block the target position
        grid[target.X, target.Y] = 0;

        var network = new TestGridNetwork();
        var pathFinder = new PathFinder(network);
        var result = pathFinder.FindPath(start, target, grid, false);

        Assert.That(result, Is.Not.Null, "PathFinder should return a path even with blocked end target.");

        const byte costBitMask = 0b0111_1111;
        for (int i = 0; i < result!.Count - 1; i++)
        {
            Assert.That(
                (grid[result[i].X, result[i].Y] & costBitMask),
                Is.GreaterThan(0),
                $"Penultimate path node at index {i} ({result[i].X},{result[i].Y}) is unwalkable.");
        }
    }

    /// <summary>
    /// Tests that same start/end returns an empty path (no movement needed).
    /// When start equals end, the PathFinder should immediately recognize
    /// arrival and return an empty collection (no steps required).
    /// </summary>
    [Test]
    public void PathValidation_SameStartAndEndReturnsEmpty()
    {
        var grid = CreateDefaultGrid();
        var same = new Point(10, 10);

        var network = new TestGridNetwork();
        var pathFinder = new PathFinder(network);
        var result = pathFinder.FindPath(same, same, grid, false);

        Assert.That(result, Is.Not.Null, "PathFinder should not return null for same start/end.");
        Assert.That(result, Is.Empty, "Path should be empty (zero steps) when start equals target.");
    }

    /// <summary>
    /// Tests that paths avoid safezone tiles when includeSafezone is false.
    /// </summary>
    [Test]
    public void PathValidation_AvoidsSafezone()
    {
        var grid = CreateDefaultGrid();
        var start = new Point(5, 3);
        var target = new Point(5, 15);

        // Mark a vertical column as safezone (set high bit)
        for (int y = 4; y < 14; y++)
        {
            grid[5, y] = (byte)(grid[5, y] | 0b1000_0000);
        }

        var network = new TestGridNetwork();
        var pathFinder = new PathFinder(network);
        var result = pathFinder.FindPath(start, target, grid, false);

        if (result is { Count: > 0 })
        {
            foreach (var node in result)
            {
                const byte safezoneBitFlag = 0b1000_0000;
                bool isSafezone = (grid[node.X, node.Y] & safezoneBitFlag) > 0;
                Assert.That(isSafezone, Is.False, $"Path includes safezone tile at ({node.X}, {node.Y})");
            }
        }
    }

    /// <summary>
    /// Validates a path against all five specification rules.
    /// </summary>
    private static void ValidatePath(IList<PathResultNode> path, byte[,] grid, Point start, Point target)
    {
        Assert.That(path, Is.Not.Null, "Path should not be null for valid start/target.");
        Assert.That(path.Count, Is.GreaterThan(0), "Path should contain at least one node.");

        int width = grid.GetLength(0);
        int height = grid.GetLength(1);
        const byte costBitMask = 0b0111_1111;

        // 1. Walkability
        // 2. Bounds
        // 3. End-at-target
        // 4. MaxPathLength
        // 5. Adjacency

        Assert.That(path.Count, Is.LessThanOrEqualTo(128), $"Path length ({path.Count}) exceeds maximum (128)");

        for (int i = 0; i < path.Count; i++)
        {
            var node = path[i];

            // Bounds check
            Assert.That(node.X, Is.LessThan(width), $"Node X={node.X} exceeds grid width={width}");
            Assert.That(node.Y, Is.LessThan(height), $"Node Y={node.Y} exceeds grid height={height}");

            // Walkability check
            byte cellValue = grid[node.X, node.Y];
            Assert.That(
                (cellValue & costBitMask),
                Is.GreaterThan(0),
                $"Path includes unwalkable tile at ({node.X}, {node.Y})");

            // Adjacency check (skip for first node since it has no predecessor)
            if (i > 0)
            {
                var prev = path[i - 1];
                int dx = Math.Abs(node.X - prev.X);
                int dy = Math.Abs(node.Y - prev.Y);
                int chebyshev = Math.Max(dx, dy);
                Assert.That(
                    chebyshev,
                    Is.EqualTo(1),
                    $"Non-adjacent path steps at index {i}: ({prev.X},{prev.Y}) -> ({node.X},{node.Y})");
            }
        }

        // End-at-target check
        var lastNode = path[^1];
        Assert.That(
            lastNode.Point,
            Is.EqualTo(target),
            $"Path end ({lastNode.X},{lastNode.Y}) does not match target ({target.X},{target.Y})");
    }

    /// <summary>
    /// Creates a default walkable terrain grid (32 columns x 32 rows, all tiles walkable with cost 1).
    /// </summary>
    private static byte[,] CreateDefaultGrid()
    {
        const int width = 48;
        const int height = 48;
        var grid = new byte[width, height];

        for (int x = 0; x < width; x++)
        {
            for (int y = 0; y < height; y++)
            {
                grid[x, y] = 1; // walkable, cost = 1
            }
        }

        return grid;
    }

    /// <summary>
    /// Runs a basic A* pathfinding test with default start/target on a walkable grid.
    /// </summary>
    private static (IList<PathResultNode> Path, byte[,] Grid) RunBasicPathfindingTest()
    {
        return RunBasicPathfindingTest(new Point(5, 5), new Point(15, 15));
    }

    /// <summary>
    /// Runs an A* pathfinding test with the specified start and target positions.
    /// </summary>
    private static (IList<PathResultNode> Path, byte[,] Grid) RunBasicPathfindingTest(Point start, Point target)
    {
        var grid = CreateDefaultGrid();
        var network = new TestGridNetwork();
        var pathFinder = new PathFinder(network);
        var path = pathFinder.FindPath(start, target, grid, false);

        Assert.That(path, Is.Not.Null, "PathFinder returned null for a fully walkable grid.");
        Assert.That(path, Has.Count.GreaterThan(0), "PathFinder returned empty path for valid start/target.");

        return (path!, grid);
    }

    #endregion

    #region Helper Methods

    /// <summary>
    /// Generates the XML doc member key for a constructor.
    /// Format: M:Namespace.Type.#ctor(ParamType1,ParamType2)
    /// </summary>
    private static string GetMethodDocKey(ConstructorInfo ctor)
    {
        var paramTypes = ctor.GetParameters()
            .Select(p => GetParameterTypeName(p.ParameterType));
        return $"M:{ctor.DeclaringType?.FullName}.#ctor({string.Join(",", paramTypes)})";
    }

    /// <summary>
    /// Generates the XML doc member key for a method.
    /// Format: M:Namespace.Type.MethodName(ParamType1,ParamType2)
    /// </summary>
    private static string GetMethodDocKey(MethodInfo method)
    {
        var paramTypes = method.GetParameters()
            .Select(p => GetParameterTypeName(p.ParameterType));
        return $"M:{method.DeclaringType?.FullName}.{method.Name}({string.Join(",", paramTypes)})";
    }

    /// <summary>
    /// Gets the XML doc-compatible parameter type name.
    /// </summary>
    private static string GetParameterTypeName(Type type)
    {
        if (type.IsGenericType)
        {
            var genericDef = type.GetGenericTypeDefinition().FullName;
            if (genericDef is null)
            {
                return type.FullName ?? type.Name;
            }

            // Strip backtick count from generic type name
            var genericBaseName = genericDef[..genericDef.IndexOf('`')];
            var typeArgs = type.GetGenericArguments()
                .Select(GetParameterTypeName);
            return $"{genericBaseName}{{{string.Join(",", typeArgs)}}}";
        }

        return type.FullName ?? type.Name;
    }

    #endregion

    #region Test Infrastructure: TestGridNetwork

    /// <summary>
    /// A minimal <see cref="BaseGridNetwork"/> implementation for testing.
    /// Caches <see cref="Node"/> instances by position so that
    /// the PathFinder can track Open/Closed status across calls.
    /// </summary>
    private sealed class TestGridNetwork : BaseGridNetwork
    {
        private readonly Dictionary<int, Node> _nodes = new();

        /// <summary>
        /// Initializes a new instance of the <see cref="TestGridNetwork"/> class.
        /// </summary>
        /// <param name="allowDiagonals">If set to <c>true</c>, diagonal movement is allowed.</param>
        public TestGridNetwork(bool allowDiagonals = true)
            : base(allowDiagonals)
        {
        }

        /// <inheritdoc />
        public override Node? GetNodeAt(Point position)
        {
            var key = (position.Y << 8) + position.X;
            if (!this._nodes.TryGetValue(key, out var node))
            {
                node = new Node
                {
                    Position = position,
                    Status = NodeStatus.Undefined,
                };
                this._nodes[key] = node;
            }

            return node;
        }

        /// <inheritdoc />
        public override bool Prepare(Point start, Point end, byte[,] grid, bool includeSafezone)
        {
            this._nodes.Clear();
            return base.Prepare(start, end, grid, includeSafezone);
        }
    }

    #endregion
}
