// <copyright file="OapsLearningLoopTests.cs" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

namespace MUnique.OpenMU.AIPlayer.Tests;

using Microsoft.Extensions.Logging.Abstractions;
using MUnique.OpenMU.AIPlayer.Decision;
using OAPS.Evolution;
using Xunit;

/// <summary>
/// Tests for the OAPS learning loop: <see cref="RuleEngine.AddLearnedRules"/>
/// and <see cref="OapsKnowledgeBridge"/> end-to-end learning pipeline.
/// </summary>
public class OapsLearningLoopTests
{
    /// <summary>
    /// RuleEngine.AddLearnedRules 正确追加规则并设置 AutoGenerated 和优先级偏移。
    /// </summary>
    [Fact]
    public void RuleEngine_AddLearnedRules_RulesAreAdded()
    {
        var scriptLib = new ScriptLibrary(null!, null!, null!, null!, NullLogger.Instance, null!);
        var engine = new RuleEngine(scriptLib, NullLogger.Instance);
        var before = engine.GetRules().Count;

        var learned = new List<RuleDef>
        {
            new("test_rule_1", 10, "survival", "HP_PCT < 0.3", "use_hp_potion", 0, 0, null, null, "test"),
        };
        engine.AddLearnedRules(learned);

        Assert.Equal(before + 1, engine.GetRules().Count);
        var added = engine.GetRules().Last();
        Assert.True(added.AutoGenerated);
        Assert.Equal(1010, added.Priority); // 10 + 1000 offset
    }

    /// <summary>
    /// SyncLearning 端到端验证：从行为事件 → 模式分析 → 规则生成 → 规则注入。
    /// 验证注入后规则表数量增加。
    /// </summary>
    [Fact]
    public void SyncLearning_WithKillEvents_InjectsRules()
    {
        // 准备 BehaviorEvent 数据（使用不同 Level 避免 BehaviorEventStore 去重）
        var store = new BehaviorEventStore(".", NullLogger.Instance);
        for (int i = 0; i < 5; i++)
        {
            store.AddEvent(new BehaviorEvent
            {
                EventType = BehaviorEventType.MonsterKilled,
                CharacterName = "TestPlayer",
                Level = 10 + i,
                MapNumber = 3,
                MonsterNumber = 67,
                MonsterName = "Spider",
                MonsterLevel = 5,
                X = 100,
                Y = 200,
            });
        }

        // 添加购药事件
        store.AddEvent(new BehaviorEvent
        {
            EventType = BehaviorEventType.PotionBought,
            CharacterName = "TestPlayer",
            Level = 10,
            ItemGroup = 14,
            ItemNumber = 1,
            ItemPrice = 100,
        });

        var scriptLib = new ScriptLibrary(null!, null!, null!, null!, NullLogger.Instance, null!);
        var engine = new RuleEngine(scriptLib, NullLogger.Instance);
        var bridge = new OapsKnowledgeBridge(store, engine, NullLogger.Instance);

        var before = engine.GetRules().Count;
        bridge.SyncLearning("TestPlayer");
        var after = engine.GetRules().Count;

        Assert.True(after > before, "学习规则应该被注入");
    }
}
